///
/// COPYRIGHT Ericsson 2021
///
///
///
/// The copyright to the computer program(s) herein is the property of
///
/// Ericsson Inc. The programs may be used and/or copied only with written
///
/// permission from Ericsson Inc. or in accordance with the terms and
///
/// conditions stipulated in the agreement/contract under which the
///
/// program(s) have been supplied.
///



export const Constants = {
    PIPELINE: 'MS Pipeline Name',
    CICD_REPORTDSB: 'MicroService RuleSet Visualisation (MRV) Dashboard',
    FEEDBACK: 'Feedback',
    FEEDBACK_URL: 'https://forms.office.com/e/vQwRgPgK3T',
    FEEDBACK_TEMPLATE: 'Feedback Form',
    SUPPORT: 'Support',
    SUPPORT_URL: 'https://eteamproject.internal.ericsson.com/browse/IDUN-114442',
    SUPPORT_TEMPLATE: 'Regulus Support Template',
    CBOS_VERSION: 'CBOS Version',
    CUSTOM_STAGES: 'Custom Stages',
    DEFAULT: 'default',
    PRODUCTS: 'products',
    HTTP_HEADER_NAME: 'Component-Id',
    MMT_FEEDBACK: 'Provide MMT Tool Feedback',
    BUILD_NUMBER: 'Build No',
    BUILD_SUCCESS_PERC: 'Alignment (%)',
    NOT_AVAILABLE: 'NA',
    NOT_AVAILABLE_SONAR: 'Reports not generated',
    VERSION_NA: "Unavailable",
    LAST_SUCCESS_BUILD_DURATION: 'Success Duration : ',
    LAST_RUN_DATE: 'Last Run Date: ',
    NAME: 'Name:',
    STATUS: 'Status:',
    ALIGN_TEXT: 'Microservice alignment to stage availability with improvement/regression/no change indicator',
    USER_GUIDE: 'User Guide',
    USER_GUIDE_URL: 'https://eteamspace.internal.ericsson.com/display/DGBase/MRV+User+Guide#UserGuide',
    HELM_VERSION: 'Helm Version',
    HELM_VERSION_TEXT:'The last Helm chart version of the microservice build',
    BUILD_NO_TEXT:'The latest successful build Number of the MS pipeline',
    CBOS_VERSION_TEXT:'The CBOS Version and its compliance with microservice',
    VA_COLUMN_TOOLTIP: 'The VA rules alignment',
    SONAR_METRICS_COLUMN: 'SonarQube Report',
    SONAR_METRICS_TOOLTIP: 'The sonar metrics are generated by successful execution of SonarQube Analysis stage',
    MS_PIPELINE_TOOLTIP: 'All the MS pipelines',
    BUGS: 'new_bugs',
    VULNERABILITIES: 'new_vulnerabilities',
    COVERAGE: 'new_coverage',
    SQALE_INDEX: 'new_technical_debt',
    VULNERABILITY_ANALYSIS: 'Vulnerability Analysis',
    SONAR_METRICS_NA_MESSAGE: 'Either it has never been analyzed successfully or it has been deleted.',
    SONAR_METRICS_NA_DEFAULT_MESSAGE: 'SonarQube stage may have missed/skipped.',
 };
