#
# COPYRIGHT Ericsson 2021
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

config:
  #Publish job type suffixes. If job name contains one of this values it is a Publish job
  publish: Publish, publish, Release, release, RELEASE
  #Label for display Publish jobs
  publishLabel: Publish
  #PreCodeReview job type suffixes. If job name contains one of this values it is a PreCodeReview job
  preCodeReview: PreCodeReview, PCR, Precode, precode, PreCode, PRE_CODE, PRECODE, precodereview, code-review
  #Label for display PreCodeReview jobs
  preCodeReviewLabel: PreCodeReview