#
# COPYRIGHT Ericsson 2021
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eric-oss-ms-maturity-visualisation.name" . }}-configmap
  labels:
  {{- include "eric-oss-ms-maturity-visualisation.labels" . | indent 4 }}
  {{- if .Values.labels }}
    {{ .Values.labels | toYaml | indent 4 }}
  {{- end }}
  annotations:
{{- include "eric-oss-ms-maturity-visualisation.prometheus" . | nindent 4 }}
{{- include "eric-oss-ms-maturity-visualisation.product-info" . | indent 4 }}
{{- include "eric-oss-ms-maturity-visualisation.config-annotations" . | indent 4 }}

data:
  application.properties: |
    management.endpoint.metrics.enabled=true
    management.endpoints.web.exposure.include=*
    management.endpoint.prometheus.enabled=true
    management.metrics.export.prometheus.enabled=true
    management.metrics.web.server.auto-time-requests=true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eric-oss-ms-maturity-visualisation.name" . }}
  labels:
{{- include "eric-oss-ms-maturity-visualisation.labels" . | nindent 4 }}
  annotations:
{{ include "eric-oss-ms-maturity-visualisation.product-info" . | indent 4 }}
{{- include "eric-oss-ms-maturity-visualisation.config-annotations" . | indent 4 }}
spec:
{{- if not .Values.autoScaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "eric-oss-ms-maturity-visualisation.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    type: {{ .Values.updateStrategy.type | quote }}
    {{- if and (eq .Values.updateStrategy.type "RollingUpdate") .Values.updateStrategy.rollingUpdate }}
    rollingUpdate:
      maxUnavailable: {{ .Values.updateStrategy.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.updateStrategy.rollingUpdate.maxSurge }}
    {{- end }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "eric-oss-ms-maturity-visualisation.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ include "eric-oss-ms-maturity-visualisation.version" . }}
      annotations:
{{ include "eric-oss-ms-maturity-visualisation.prometheus" . | nindent 8 }}
{{ include "eric-oss-ms-maturity-visualisation.product-info" . | indent 8 }}
{{- include "eric-oss-ms-maturity-visualisation.config-annotations" . | indent 8 }}
    spec:
      {{- if .Values.podPriority.maturity.priorityClassName }}
      priorityClassName: {{ .Values.podPriority.maturity.priorityClassName | quote }}
      {{- end }}
      {{- if include "eric-oss-ms-maturity-visualisation.pullSecret" . }}
      imagePullSecrets:
        - name: {{ include "eric-oss-ms-maturity-visualisation.pullSecret" . | quote}}
      {{- end }}
      serviceAccountName: {{ template "eric-oss-ms-maturity-visualisation.fullname" . }}
      {{- if .Values.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds:
        {{- include "eric-oss-ms-maturity-visualisation.terminationGracePeriodSeconds" . | nindent 8 }}
      {{- end }}
      securityContext:
        fsGroup: {{ include "eric-oss-ms-maturity-visualisation.fsGroup.coordinated" . }}
      volumes:
        - name: scripts
          configMap:
            name: {{ template "eric-oss-ms-maturity-visualisation.name" . }}-script
            defaultMode: 0777
        - name: config-volume
          configMap:
            name: {{ include "eric-oss-ms-maturity-visualisation.name" . }}-configmap
        - name: tmp-volume
          emptyDir: {}
      containers:
        {{ $dbConfig := index .Values "eric-oss-ms-maturity-visualisation-data" }}
        - name: eric-oss-ms-maturity-visualisation
          image: {{ template "eric-oss-ms-maturity-visualisation.mainImagePath" . }}
          imagePullPolicy: {{ .Values.global.registry.imagePullPolicy | quote }}
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - all
          volumeMounts:
            - name: config-volume
              mountPath: /config
            - name: tmp-volume
              mountPath: /tmp
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            failureThreshold: {{ .Values.probes.termination.livenessProbe.failureThreshold }}
            initialDelaySeconds: {{ .Values.probes.termination.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.termination.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.termination.livenessProbe.timeoutSeconds }}
            httpGet:
              path: /actuator/health
              port: http
          readinessProbe:
            initialDelaySeconds: {{ .Values.probes.termination.readinessProbe.initialDelaySeconds }}
            failureThreshold: {{ .Values.probes.termination.readinessProbe.failureThreshold }}
            periodSeconds: {{ .Values.probes.termination.readinessProbe.periodSeconds }}
            successThreshold: {{ .Values.probes.termination.readinessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.probes.termination.readinessProbe.timeoutSeconds }}
            httpGet:
              path: /actuator/health
              port: http
          env:
          - name: TZ
            value: {{ template "eric-oss-ms-maturity-visualisation.timezone" . }}
          - name: JENKINS_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ $dbConfig.credentials.kubernetesSecretName }}
                key: jenkins-username
          - name: JENKINS_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ $dbConfig.credentials.kubernetesSecretName }}
                key: jenkins-token
  {{- if .Values.global }}
        {{- if .Values.global.security }}
          {{- if .Values.global.security.tls }}
            {{- if .Values.global.security.tls.enabled }}
          - name: CONNECT_MODE
            value: "tls"
            {{- if (eq .Values.service.endpoints.chassisapi.tls.enforced "required") }}
          - name: TLS_MODE
            value: "only_tls"
            {{- if (eq .Values.service.endpoints.chassisapi.tls.verifyClientCertificate "required") }}
          - name: TLS_CA
            value: "ca_path"
            {{- end }}
            {{- end }}
            {{- end }}
          {{- end }}
        {{- end }}
      {{- end }}
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ $dbConfig.credentials.kubernetesSecretName }}
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ $dbConfig.credentials.kubernetesSecretName }}
                key: password
          - name: DB_DRIVER_CLASS_NAME
            value: org.postgresql.Driver
          - name: DB_URL
            value: jdbc:postgresql://{{ $dbConfig.name }}:{{ $dbConfig.service.port }}/{{ $dbConfig.postgresDatabase }}
          - name: PGDATABASE
            value: {{ $dbConfig.postgresDatabase }}
          - name: ENV
            value: prod
          resources:
            requests:
            {{- if (index .Values "resources" "eric-oss-ms-maturity-visualisation" "requests" "cpu") }}
              cpu: {{ (index .Values "resources" "eric-oss-ms-maturity-visualisation" "requests" "cpu" | quote) }}
            {{- end }}
            {{- if (index .Values "resources" "eric-oss-ms-maturity-visualisation" "requests" "memory") }}
              memory: {{ (index .Values "resources" "eric-oss-ms-maturity-visualisation" "requests" "memory" | quote) }}
            {{- end }}
            {{- if (index .Values "resources" "eric-oss-ms-maturity-visualisation" "requests" "ephemeral-storage") }}
            {{ println "  ephemeral-storage:" (index .Values "resources" "eric-oss-ms-maturity-visualisation" "requests" "ephemeral-storage" | quote) }}
            {{- end }}
            limits:
            {{- if (index .Values "resources" "eric-oss-ms-maturity-visualisation" "limits" "cpu") }}
              cpu: {{ (index .Values "resources" "eric-oss-ms-maturity-visualisation" "limits" "cpu" | quote) }}
            {{- end }}
            {{- if (index .Values "resources" "eric-oss-ms-maturity-visualisation" "limits" "memory") }}
              memory: {{ (index .Values "resources" "eric-oss-ms-maturity-visualisation" "limits" "memory" | quote) }}
            {{- end }}
            {{- if (index .Values "resources" "eric-oss-ms-maturity-visualisation" "limits" "ephemeral-storage") }}
            {{ println "  ephemeral-storage:" (index .Values "resources" "eric-oss-ms-maturity-visualisation" "limits" "ephemeral-storage" | quote) }}
            {{- end }}
      nodeSelector: {{ include "eric-oss-ms-maturity-visualisation.nodeSelector" . | nindent 6 -}}
      {{- if .Values.tolerations}}
      tolerations:
        {{- include "eric-oss-ms-maturity-visualisation.tolerations" . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints.deployment }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- if eq .Values.affinity.podAntiAffinity "hard" }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ include "eric-oss-ms-maturity-visualisation.name" . }}
            topologyKey: "kubernetes.io/hostname"
      {{- else if eq .Values.affinity.podAntiAffinity  "soft" }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - {{ include "eric-oss-ms-maturity-visualisation.name" . }}
              topologyKey: "kubernetes.io/hostname"
      {{- end }}
