#
# COPYRIGHT Ericsson 2021
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

{{ if (index .Values "eric-oss-ms-maturity-visualisation-data" "enabled") }}
{{ $dbConfig := index .Values "eric-oss-ms-maturity-visualisation-data" }}
{{ $superPassword := default (randAlphaNum 20) $dbConfig.postgresSuperPassword | b64enc | quote }}
{{ $password := default (randAlphaNum 20) $dbConfig.postgresPassword | b64enc | quote }}
{{ $jenkinsUsername := default "" .Values.jenkins.username | b64enc | quote }}
{{ $jenkinsToken := default "" .Values.jenkins.token | b64enc | quote }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace "eric-oss-ms-maturity-visualisation") }}
{{- if $secret }}
{{- if index $secret.data "super-password" }}
{{- $superPassword = index $secret.data "super-password" }}
{{- end }}
{{- if index $secret.data "password" }}
{{- $password = index $secret.data "password" }}
{{- end }}
{{- if index $secret.data "jenkins-username" }}
{{ $jenkinsUsername = index $secret.data "jenkins-username" }}
{{- end }}
{{- if index $secret.data "jenkins-token" }}
{{ $jenkinsToken = index $secret.data "jenkins-token" }}
{{- end }}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "eric-oss-ms-maturity-visualisation.name" . }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name | quote }}
    app.kubernetes.io/version: {{ include "eric-oss-ms-maturity-visualisation.version" . }}
    helm.sh/chart: {{ template "eric-oss-ms-maturity-visualisation.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    {{- include "eric-oss-ms-maturity-visualisation.product-info" . | indent 4 }}
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
data:
  username: {{ index .Values "eric-oss-ms-maturity-visualisation-data" "postgresUser" | b64enc | quote }}
  password: {{ $password }}
  jenkins-username: {{ $jenkinsUsername }}
  jenkins-token: {{ $jenkinsToken }}
  super-password: {{ $superPassword }}
  metrics-user: {{ default "exporter"  $dbConfig.metricsUser | b64enc | quote }}
  metrics-pwd: {{ default (randAlphaNum 20) $dbConfig.metricsPwd | b64enc | quote }}
  replica-user: {{ default "replica" $dbConfig.replicaUser | b64enc | quote }}
  replica-pwd: {{ default (randAlphaNum 20) $dbConfig.replicaPwd | b64enc | quote }}
{{ end }}
