#
# COPYRIGHT Ericsson 2021
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "eric-oss-ms-maturity-visualisation.fullname" . }}
  labels:
    {{- include "eric-oss-ms-maturity-visualisation.labels" . | indent 4 }}
    {{- if .Values.labels }}
      {{ .Values.labels | toYaml | indent 4 }}
    {{- end }}
  annotations:
{{- include "eric-oss-ms-maturity-visualisation.product-info" . | indent 4 }}
{{- include "eric-oss-ms-maturity-visualisation.config-annotations" . | indent 4 }}
{{- end }}